CREATE TABLE IF NOT EXISTS sessions (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 token_hash TEXT NOT NULL UNIQUE, user_name TEXT NOT NULL,
 expires BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS sessions_expiry ON sessions(expires);
CREATE TABLE IF NOT EXISTS login_attempts (
 user_name TEXT PRIMARY KEY, count INTEGER NOT NULL, expires BIGINT NOT NULL
);
CREATE TABLE IF NOT EXISTS schedules (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 owner TEXT NOT NULL CHECK(owner IN ('Moreno','Cahya')),
 day INTEGER NOT NULL CHECK(day BETWEEN 1 AND 7),
 start TEXT NOT NULL,
 "end" TEXT NOT NULL CHECK("end" > start),
 course TEXT NOT NULL,
 lecturer TEXT NOT NULL DEFAULT '',
 room TEXT NOT NULL DEFAULT ''
);
CREATE TABLE IF NOT EXISTS tasks (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 title TEXT NOT NULL,
 deadline TEXT NOT NULL,
 assignee TEXT NOT NULL CHECK(assignee IN ('Moreno','Cahya','Berdua')),
 priority TEXT NOT NULL CHECK(priority IN ('Rendah','Sedang','Tinggi')),
 done INTEGER NOT NULL DEFAULT 0 CHECK(done IN (0,1))
);

CREATE TABLE IF NOT EXISTS budget_records (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 kind TEXT NOT NULL CHECK(kind IN ('transaction','limit','reminder','goal')),
 data TEXT NOT NULL,
 created_by TEXT NOT NULL CHECK(created_by IN ('Moreno','Cahya'))
);
